export default function Main() {
  return (
    <div className="container">
      <h2 className="title">Главная</h2>
      <article className="article"><h4 className="article-title">Article 1</h4>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Architecto corrupti aut repudiandae nobis dicta non deleniti ipsa? Perspiciatis porro, repudiandae autem exercitationem corporis dicta vero, officiis neque quaerat doloribus molestiae facere suscipit beatae voluptates eum? Et, veritatis, delectus repellendus porro asperiores modi non ex obcaecati deserunt aliquam expedita, quis illo!</article>
      <article className="article"><h4 className="article-title">Article 2</h4>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque nulla tenetur adipisci, enim accusamus alias voluptate nam blanditiis at reiciendis. Accusantium et at veritatis voluptatum, obcaecati mollitia quia iusto corrupti laudantium, atque officiis architecto quaerat accusamus perspiciatis blanditiis nemo autem. Quisquam temporibus repellat magnam dicta dignissimos accusamus nostrum ullam facere ducimus ex, labore deserunt minus dolore, debitis eius deleniti quaerat incidunt! In nisi quas facilis similique. Expedita nobis reiciendis quas!</article>
      <article className="article"><h4 className="article-title">Article 3</h4>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque nulla tenetur adipisci, enim accusamus alias voluptate nam blanditiis at reiciendis. Accusantium et at veritatis voluptatum, obcaecati mollitia quia iusto corrupti laudantium, atque officiis architecto quaerat accusamus perspiciatis blanditiis nemo autem. Quisquam temporibus repellat magnam dicta dignissimos accusamus nostrum ullam facere ducimus ex, labore deserunt minus dolore, debitis eius deleniti quaerat incidunt! In nisi quas facilis similique. Expedita nobis reiciendis quas! Lorem ipsum dolor sit amet consectetur adipisicing elit. Non similique quidem veritatis nisi eos. Aliquam mollitia non, pariatur corporis quam incidunt impedit laboriosam necessitatibus reiciendis soluta harum error. Consequuntur, quas.</article>
      <article className="article"><h4 className="article-title">Article 4</h4>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque nulla tenetur adipisci, enim accusamus alias voluptate nam blanditiis at reiciendis. Accusantium et at veritatis voluptatum, obcaecati mollitia quia iusto corrupti laudantium, atque officiis architecto quaerat accusamus perspiciatis blanditiis nemo autem. </article>
    </div>
  );
}